### ISSUE TITLE
Migrate to src layout

### ISSUE THREAD

**Issue by YuevUwU** [SCAICT/SCAICT-uwu#163]
As projects grow more complex, we will need better maintainability.   
Therefore, it would be a nice try to consider modifying the project layout.  

( The plan was first mentioned by @winstonsung )

> **__@YuevUwU wrote:__**
> Any plan about migrating code to src folder, or develop in original path?

> **__@winstonsung wrote:__**
> The current plan is to migrate code to the src folder.
> There were attempts about using the flat layout, but it turns out to be more complicated than the src layout, thus being reverted.

## To-do

- [ ] Discuss whether and when to proceed
- [ ] Modify codes to conform the src layout
- [ ] Perform thorough testing to confirm that the migration does not break existing functionality
- [ ] Updated guide/docs to reflect the new structure

## See also

- #91
