### ISSUE TITLE
Add Pylint CI

### ISSUE THREAD

**Issue by winstonsung** [SCAICT/SCAICT-uwu#37]
Add Pylint GitHub Actions CI.

https://github.com/actions/starter-workflows/blob/607f368/ci/pylint.yml
```[tasklist]
### Tasks
- [ ] https://github.com/SCAICT/SCAICT-uwu/issues/47
- [ ] https://github.com/SCAICT/SCAICT-uwu/pull/38
- [ ] https://github.com/SCAICT/SCAICT-uwu/pull/44
- [ ] https://github.com/SCAICT/SCAICT-uwu/pull/40
- [ ] https://github.com/SCAICT/SCAICT-uwu/pull/41
- [ ] https://github.com/SCAICT/SCAICT-uwu/pull/45
- [ ] https://github.com/SCAICT/SCAICT-uwu/pull/46
- [ ] https://github.com/SCAICT/SCAICT-uwu/pull/50
- [ ] https://github.com/SCAICT/SCAICT-uwu/pull/53
- [ ] https://github.com/SCAICT/SCAICT-uwu/pull/60
```

**Comment by winstonsung** [comment]
Decided docstring format:

```py
"""
Summary line.

Extended description.

Parameters:
    param_1 (int): Description of param_1.
    param_2 (str): Description of param_2.

Returns:
    bool: Description of return value.

Raises:
    KeyError: raises an exception.
"""
```

**Comment by winstonsung** [comment]
Unit tests:

https://docs.python.org/3/library/unittest.html
